global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5m

receivers:
  - name: 'default'
    slack_configs:
      - api_url: 'https://hooks.sl
