server:
  port: 19090
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    hostname: eureka-server
    prefer-ip-address: false