# Kafka test controller api list

### tempCreateReservationMessageProducer
GET http://localhost:19040/api/test/kafka/create-reservation-result?reservationId=ac197001-9449-1963-8194-49d9f1400000


### t1
GET http://localhost:19040/api/test/kafka/t1

### t2
GET http://localhost:19040/api/test/kafka/t2?topic=topicF&key=
Content-Type: application/json

{
  "name" : "피카",
  "status" : "휴식",
  "reservationStatus" : "COMPLETED"
}