spring:
  application:
    name: temple-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        type: trace
        default_schema: temples
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      password: systempass
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
      database: 0

    elasticsearch:
      host: localhost:9200
      username: elastic
      password: password
      repositories:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19020