# CreateReservation controller api list

### createReservation
POST http://localhost:19040/api/reservations
Content-Type: application/json
X-Login-Id: tempUserId77
X-User-Role: MEMBER
X-Token: token value something

{
  "userId" : "afb0f818-0909-4d6c-a89c-50a576160702",
  "programId" : "683ef0bb-c2d0-4379-8e10-78914ed85f13",
  "programDate" : "2025-01-01",
  "couponUsedType": "USED",
  "couponId" : "9745ad8d-2f74-46da-a7fd-58a69b45d0ba",
  "name" : "삐까2",
  "phoneNumber" : "010-333-7777",
  "gender" : "FEMALE",
  "paymentType": "NO_PAY",
  "paymentStatus": "COMPLETED"
}