@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MzY2MDk1MDUsImV4cCI6MTczNjYxMTMwNSwibG9naW5JZCI6InRlc3QxMjM0Iiwicm9sZSI6IlRFTVBMRV9BRE1JTiIsInR5cGUiOiJhY2Nlc3MifQ.Hq9UgA4p9JineSERbgIzpUNUARFg2oR_St9fot9bhO8
@page = 0
@size = 10
@sortBy = createdAt

### 리뷰 작성
POST http://localhost:19091/api/reviews
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "reservationId": "7f000001-9455-1caf-8194-56027b160001",
  "content": "재밌었어요. 위치도 좋고, 풍경도 멋있어 힐링하고 왔네요",
  "rating": 1.0
}

### 본인이 작성한 리뷰 조회
GET http://localhost:19091/api/reviews/me?page={{page}}&size={{size}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json


### 프로그램별 리뷰 조회
@programId = 2560006b-0962-4950-8ea7-c6babddffce3

GET http://localhost:19091/api/reviews?programId={{programId}}&page={{page}}&size={{size}}&sortBy={{sortBy}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 작성한 리뷰 수정
@reviewId = a1883c79-252a-419f-ac2a-ccc4ab019bf2

PATCH http://localhost:19091/api/reviews/{{reviewId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "content": "ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ재밌었어요. 위치도 좋고, 풍경도 멋있어 힐링하고 왔네요",
  "rating": 1.0
}