### 회원가입 - MEMBER1
POST http://localhost:19091/api/users/sign-up
Content-Type: application/json

{
  "loginId" : "test1234",
  "email": "test@naver.com",
  "password": "Test1234!!",
  "userName": "홍길동",
  "nickName" : "길동이",
  "gender": "MALE",
  "birth" : "1990-01-31",
  "role" : "MEMBER",
  "phone" : "010-1234-1234"
}

### 회원가입 - MEMBER2
POST http://localhost:19091/api/users/sign-up
Content-Type: application/json

{
  "loginId" : "test9999",
  "email": "test9999@naver.com",
  "password": "Test1234!!",
  "userName": "김아무개",
  "nickName" : "아무개",
  "gender": "MALE",
  "birth" : "1995-01-31",
  "role" : "MEMBER",
  "phone" : "010-1234-9999"
}

### 회원가입 - TEMPLE_ADMIN
POST http://localhost:19091/api/users/sign-up
Content-Type: application/json

{
  "loginId" : "admin1000",
  "email": "admin1000@naver.com",
  "password": "Admin1234!!",
  "userName": "김혜민",
  "nickName" : "스님1",
  "gender": "MALE",
  "birth" : "1960-10-31",
  "role" : "TEMPLE_ADMIN",
  "phone" : "010-5678-9090"
}

### 회원가입 - MASTER
POST http://localhost:19091/api/users/sign-up
Content-Type: application/json

{
  "loginId" : "master9999",
  "email": "master9999@naver.com",
  "password": "Master9999!!",
  "userName": "김갑수",
  "nickName" : "최강관리자",
  "gender": "MALE",
  "birth" : "1995-01-31",
  "role" : "MASTER",
  "phone" : "010-1234-1234"
}

### 로그인 - MEMBER1
POST http://localhost:19091/api/auth/login
Content-Type: application/json

{
  "loginId": "test1234",
  "password": "Test1234!!"
}

### 로그인 - MEMBER2
POST http://localhost:19091/api/auth/login
Content-Type: application/json

{
  "loginId": "test9999",
  "password": "Test1234!!"
}

### 로그인 - TEMPLE_ADMIN
POST http://localhost:19091/api/auth/login
Content-Type: application/json

{
  "loginId" : "admin1000",
  "password": "Admin1234!!"
}

### 로그인 - MASTER
POST http://localhost:19091/api/auth/login
Content-Type: application/json

{
  "loginId" : "master9999",
  "password": "Master9999!!"
}