### Create Promotion
POST http://localhost:19050/api/promotion
Content-Type: application/json

{
  "name": "뉴 핫딜 프로모션",
  "type": "HOTDEAL",
  "startDate": "2025-01-01",
  "endDate": "2025-01-10",
  "couponType": "DISCOUNT",
  "maleCoupon": 100,
  "femaleCoupon": 100,
  "totalCoupon": 200
}

> {%
    // 응답에서 promotionId 추출하여 변수 저장
    client.global.set("promotionId", response.body.promotionId);
%}

###

### Update Promotion
PATCH http://localhost:19050/api/promotion/{{promotionId}}
Content-Type: application/json

{
  "name": "수정된 핫딜 프로모션",
  "startDate": "2024-01-05",
  "endDate": "2024-01-15",
  "maleCoupons": 120,
  "femaleCoupons": 120,
  "totalCoupons": 240,
  "couponType": "DISCOUNT"
}

###

### Get Promotions with Pagination and Filters
GET http://localhost:19050/api/promotion?page=0&size=10&type=HOTDEAL&status=ACTIVE

###

### Get Promotion by ID
GET http://localhost:19050/api/promotion/{{promotionId}}

###

### Delete Promotion
DELETE http://localhost:19050/api/promotion/{{promotionId}}
